Support regex in host / server
umputun/reproxy pull request #113
Opened 2021-11-03 20:59 UTC by alek-sys

Main consideration is backward compatibility. example.com should be treated as an exact
match, where possible. So current order is: exact host, regex host, * or ""

2021-11-03 22:15 UTC, umputun requested changes
thx. Generally, it looks like a worakable solution, just a few suggestions

2021-11-03 22:15 UTC, umputun commented on app/discovery/discovery.go
> +	for mapperServer, mapper := range mappers {
you can likely just do map's lookup first to prevent loop on mappers for strict match

2021-11-03 22:15 UTC, umputun commented on app/discovery/discovery_test.go
> -	svc := NewService([]Provider{p1, p2}, time.Millisecond*100)
I'd suggest to make it a separate test, smth like TestService_MatchServerRegex

2021-11-04 10:11 UTC, alek-sys commented
Thanks! The PR is now updated based on your comments.

2021-11-04 16:18 UTC, umputun requested changes
a minor thing about tests, likely leftovers. And one more missing thing - we need to document this new functionality in the README

2021-11-04 16:18 UTC, umputun commented on app/discovery/discovery_test.go
> +	p3 := &ProviderMock{
i think p3 is a leftover from the prev combined test

2021-11-04 16:41 UTC, alek-sys commented
Yep, indeed these are leftovers. Now removed and README updated.

2021-11-04 16:45 UTC, umputun approved these changes
LGTM, thx

2021-11-04 16:46 UTC, umputun commented
before I merge it in, could you pls squash the commits?

2021-11-04 16:57 UTC, alek-sys commented
Now squashed.

2021-11-04 17:00 UTC, merged